[package]
name = "images_from_images2_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.13"
log = "0.4"
image = "0.24"
bytemuck = { version = "1.7", features = [ "derive" ] }